#!/usr/bin/env python3

import os
import sys
import argparse

import tests.base as t

parser = argparse.ArgumentParser()
parser.add_argument("-m", choices=["save", "check"])
parser.add_argument("testdir", nargs="*")
parser.parse_args("testdir".split())
args = parser.parse_args()

for testdir in args.testdir:
    success = t.init(testdir, args.m == "save")
    if not success:
        sys.exit(1)

    success = t.run()
    if not success:
        sys.exit(1)
    t.cleanup()
