#!/usr/bin/env python3
import os
import sys
import pickle
import argparse

import tests.base as t

parser = argparse.ArgumentParser()
parser.add_argument("-m", choices=["save", "check"])
parser.add_argument("testdir", nargs="*")
parser.parse_args("testdir".split())
args = parser.parse_args()


for testdir in args.testdir:
    with open("common/runtest_args.pckl", "wb") as args_file:
        pickle.dump((testdir, args.m), args_file)

    success = t.init(testdir, args.m)
    if not success:
        sys.exit(1)

    success = t.run(testdir, args.m)
    if not success:
        sys.exit(1)
    t.cleanup(testdir, args.m)
