#!/usr/bin/env python3
import os
import argparse

import tests.base as t


def main():
    for protocol in args.testdir:  # cf-ospf-base + check
        success = t.init(protocol, args.m == "save")
        if not success:
            break

        success = t.run()
        if not success and not BATCH:
            break
        t.cleanup()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-m", choices=["save", "check", "batch"])
    parser.add_argument("testdir", nargs="*")
    parser.parse_args("testdir".split())
    args = parser.parse_args()
    BATCH = args.m == "batch"
    main()
