version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Update system
          command: |
            sudo apt-get -y update
            sudo apt-get -y upgrade
            sudo apt-get -y install autoconf \
                build-essential \
                flex \
                bison \
                ncurses-dev \
                libreadline-dev