#!/bin/sh
KEY=$1
DEVICE=$2
FILE="$1-$2"
SAVED="$3/$FILE"
CHECKED="temp/$FILE"
MOD=$4

if [ $KEY = "krt" -a $MOD = "save" ]; 
    then ip netns exec $DEVICE ip -4 route show > "$SAVED"

elif [ $KEY = "krt" -a $MOD = "check" ];
    then ip netns exec $DEVICE ip -4 route show > "$CHECKED"

elif [ $KEY = "bird" -a $MOD = "save" ]; 
    then cd $DEVICE && ./birdc -l show route > "../$SAVED"
    .././tests/strip_version "../$SAVED"
    .././tests/strip_addresses "../$SAVED"
    .././tests/strip_timestamp "ospf4" "../$SAVED"
    .././tests/strip_timestamp "ospf6" "../$SAVED"
    .././tests/strip_timestamp "static4" "../$SAVED"
    .././tests/strip_timestamp "static6" "../$SAVED"

elif [ $KEY = "bird" -a $MOD = "check" ]; 
    then cd $DEVICE && ./birdc -l show route > "../$CHECKED"
    .././tests/strip_version "../$CHECKED"
    .././tests/strip_addresses "../$CHECKED"
    .././tests/strip_timestamp "ospf4" "../$CHECKED"
    .././tests/strip_timestamp "ospf6" "../$CHECKED"
    .././tests/strip_timestamp "static4" "../$CHECKED"
    .././tests/strip_timestamp "static6" "../$CHECKED"
fi
