#!/usr/bin/python3
import sys
from typing import List
from pprint import pprint


def main():
    secondary = []
    unsorted_table = load_tables()

    for index, line in enumerate(unsorted_table):
        if select_secondary_route(line):
            secondary.append(unsorted_table[index] + unsorted_table[index + 1])

    sorted_table = replace_unsorted_route(unsorted_table, sorted(secondary))
    write_table_as_txt(sorted_table)


def load_tables() -> List[str]:
    """Get table as stdin and save it into the list"""

    return [line for line in sys.stdin]


def select_secondary_route(line: str) -> str:
    """Find secondary route according to the specified conditions"""

    if "unicast" in line and "[i]" in line and "*" not in line:
        return line


def replace_unsorted_route(unsorted: List[str], sort: List[str]) -> List[str]:
    """Update unsorted list with sorted secondary routes"""

    sorted_index = 0
    for index, line in enumerate(unsorted):
        if select_secondary_route(line):
            line_1, line_2 = sort[sorted_index].split("\t")
            unsorted[index] = line_1
            unsorted[index + 1] = f"\t{line_2}"
            sorted_index += 1

    return unsorted


def write_table_as_txt(table: List[str]) -> None:
    with open(f"../{file_name}", "w") as txt_f:
        for line in table:
            txt_f.write(line)


if __name__ == "__main__":
    file_name = sys.argv[1]
    main()
