#!/bin/sh
strip_version() {
    # remove version of Bird
    sed "s/^BIRD v.* ready.$/BIRD <removed> ready./";
}

strip_timestamp() {
    # remove the timestamp from the output
    sed -E "s/[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}]/<removed>]/";
}

strip_addresses() {
    # remove the cast link-local addresses
    sed "s/\([^[:alnum:]]fe80::\)[[:alnum:]:]*\( [[:alnum:]]*\)/\1<removed>\2/;s/[^[:alnum:]]\(fe80::<removed> on\) [[:alnum:]]*/ \1 <removed>/"
}

strip_interfaces() {
    # remove the name of interfaces
    sed "s/\(nexthop .* dev\)\s[[:alnum:]]* \(.*\)/\1 <removed> \2/"
}
