#!/bin/sh

FILE="$1-$2"
OUTPUT="$3/$FILE"
KEY=$1
DEVICE=$2

if [ $KEY = "krt" ]; then
    ip netns exec $DEVICE ip -4 route show > "temp/$OUTPUT"
elif [ $KEY = "bird" ]; then
    cd $DEVICE && ./birdc -l show route > "../temp/$OUTPUT"
fi

# remove the timestamp from the output
# sed -Ei "s/(\[[a-zA-Z0-9]{5,7}\s[0-9]{2}\:[0-9]{2}\:[0-9]{2}\.[0-9]{3}\]|\[[a-zA-Z]{4,6}([0-9]{1}|[0-9]{1}\_[0-9]{1})\s[0-9]{2}\:[0-9]{2}\:[0-9]{2}\.[0-9]{3}\s+[a-z]{4}\s[0-9]{2}\.[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}\]|\[[a-zA-Z]{4,6}([0-9]{1}|[0-9]{1}\_[0-9]{1})\s[0-9]{2}\:[0-9]{2}\:[0-9]{2}\.[0-9]{3}\s+[a-z]{4}\s[0-9]{4}\:[a-z0-9]{3,4}\:[a-z0-9]{1,4}\:[a-z0-9]{1,4}\:[a-z0-9]{0,4}\:[a-z0-9]{1,4}\])/<removed>/" "../$3/$2"
